### ISSUE TITLE
request: toggle drawer mode

### ISSUE THREAD

**Issue by bbtdev** [Shougo/defx.nvim#13]
I know about this http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/

But sometimes (a lot of times) it's nice to have a drawer also, for exploring a big project. That's why I also have nerdtree besides defx. Are you open to implement such a feature?

**Comment by Shougo** [comment]
Of course, it is already todo listed behavior.
The feature is available in vimfiler.
`:help VimFilerExplorer`

**Comment by bbtdev** [comment]
It would be awesome if:
- in drawer buffer, you always have a full tree view of project, it expands folders on open
- in normal Defx buffer, you move folder to folder

If that makes any sense

**Comment by DanSnow** [comment]
Hi, I wrote a vim function to toggle defx

```vim
fun! Defx#toggle()
  if bufwinnr('defx') > 0
    execute "bdelete " . bufnr('defx')
  else
    leftabove vert split
    Defx
    vert resize 25
  endif
endfun
```
![image](https://user-images.githubusercontent.com/5575082/45732931-21109180-bc11-11e8-995d-5ae3a0e92a4b.png)

**Comment by bbtdev** [comment]
@DanSnow can you have different keybindings for drawer/toggled

**Comment by DanSnow** [comment]
@bbtdev Yeah, just change the `<F2>` with what you want in

```vim
noremap <F2> :call Defx#toggle()<CR>
```

**Comment by Shougo** [comment]
:Defx -toggle will be implemented.
Please wait.

**Comment by DanSnow** [comment]
ありがとうございます

**Comment by bbtdev** [comment]
@DanSnow I mean like when you are in the toggle buffer to have different key bindings

**Comment by Shougo** [comment]
I have added `Defx -toggle`.

**Comment by kristijanhusak** [comment]
@Shougo calling `Defx -toggle` from another window/buffer while defx buffer is opened in vertical split (Drawer mode) causes defx buffer to get full screen and blocks opening any files.

**Comment by Shougo** [comment]
I have fixed the behavior.

**Comment by kristijanhusak** [comment]
@Shougo will you implement an exact option that will use defx as project drawer?
I know there's `-split`, `-winwidth`, etc, but it still doesn't behave really well. Here's few things that bothers me:

* when `set equalalways` is enabled, defx get's resized. Solution is to use `winfixwidth`
* opening file that already exists in another split window causes opening that file twice, instead just focusing the existing split window

**Comment by Shougo** [comment]
> when set equalalways is enabled, defx get's resized. Solution is to use winfixwidth

I will fix it later.

**Comment by Shougo** [comment]
> will you implement an exact option that will use defx as project drawer?

Yes.

> opening file that already exists in another split window causes opening that file twice, instead just focusing the existing split window

I will check the behavior.

**Comment by Shougo** [comment]
> when set equalalways is enabled, defx get's resized. Solution is to use winfixwidth

Fixed.

> opening file that already exists in another split window causes opening that file twice, instead just focusing the existing split window

Please use the mapping.

```
nnoremap <silent><buffer><expr> <CR>  defx#do_action('open', 'wincmd w \| drop')
```

**Comment by kristijanhusak** [comment]
Thanks, that fixes it.

**Comment by gcollura** [comment]
Is it possible to have `do_action` to use `vim-choosewin` to select the target window? (like vimfiler)

**Comment by Shougo** [comment]
choose_win is not supported.

**Comment by hrsh7th** [comment]
I think defx has enough extensibility for open action.

you can use custom open command like `do_action('open', 'MyCustomOpenCommand'); `.

See below example.

```VimL
  function! MyDefxOpenCommand(cmd, path)
    let winnrs = range(1, tabpagewinnr(tabpagenr(), '$'))
    if len(winnrs) > 1
      for winnr in winnrs
        if index(['deol', 'vimfiler', 'defx', 'denite'], getbufvar(winbufnr(winnr), '&filetype')) == -1
          execute printf('%swincmd w', winnr)
          execute printf('%s %s', a:cmd, a:path)
          return
        endif
      endfor
    endif

    " can't find suitable buffer.
    execute printf('edit %s', a:path)
  endfunction

  command! -nargs=* -range  MyDefxOpen call MyDefxOpenCommand('edit', <q-args>)
  command! -nargs=* -range  MyDefxVsplit call MyDefxOpenCommand('vsplit', <q-args>)
  command! -nargs=* -range  MyDefxSplit call MyDefxOpenCommand('split', <q-args>)
```

Sorry for my poor english...

**Comment by azhi** [comment]
Sorry if I'm posting this in wrong place, not sure where to put this.

I'm trying to use Defx as a project drawer (`:Defx -toggle -split=vertical -winwidth=40`) and Denite as a grep tool with suspend/resume (`:Denite -post-action=suspend -auto-resume grep...`) in neovim.
The issue I'm having is that after selecting two options from denite window on attempt to select third option it is replacing Defx buffer instead of opening in edit buffer that I just switched from.
I've recorded a [gif](https://imgur.com/a/kVhxNmL), hopefully it will make what i'm trying to describe clearer.

The issue seems to be that Defx somehow steal 'focus' from the active buffer. I've tried to debug it on Denite side and confirmed that `vim.current.buffer.number` in python API actually points to Defx buffer.

I'm running neovim 0.3.1 with latest defx and denite btw.

Does somebody have same behaviour, or maybe somebody has an idea how to debug it further?
Thanks.

**Comment by Shougo** [comment]
@azhi  Please create the new issue with the minimal init.vim and the reproduce-able instruction.
I will test it later.
Your report doesn't reproduce-able for others unfortunately.

**Comment by azhi** [comment]
Nope, launched `:Denite` command when focus was on buffer with a file.
Working on new issue with reproducible steps.

**Comment by azhi** [comment]
Opened #39

**Comment by miguelsaldivar** [comment]
Any status on this?

**Comment by Shougo** [comment]
This is the next major feature of defx.
The implementation priority is high.

But I have worked for denite.nvim.

> Or should this be closed with the addition `Defx -toggle`

It is closed when defx supports tree feature.  Currently not.

**Comment by miguelsaldivar** [comment]
Thanks for the quick response, but okay that sounds great :+1:. Keep up the good work.

**Comment by Shougo** [comment]
I have added tree support.
