### ISSUE TITLE
[feature]Each tab should remeber its defx window status.

### ISSUE THREAD

**Issue by jinleileiking** [Shougo/defx.nvim#217]
I often work with tab for projects:

tab 1 : rust project with rust project defx window
tab 2: c project with c project defx window

But now , all the tabs uses one defx window. When `gt` cannot change the defx window that I want ( which nerd have this feature).

**Comment by jinleileiking** [comment]
Seems find a bug. Closed for now

**Comment by Shougo** [comment]
I have fixed the bug.

**Comment by bunnyfly** [comment]
@Shougo - I just updated, but still see this problem. If I have multiple tabs, one defx buffer is shared between them. Is there a setting I need to set in my `.vimrc` or is the bug fix still pending?

**Comment by Shougo** [comment]
@bunnyfly If you need to sepatate defx buffers by tabs, you need to change `-buffer-name` in tabs.

```
Defx -buffer-name=`'defx' . tabpagenr()`
```

**Comment by bunnyfly** [comment]
That works! Thank you! 🙌

**Comment by Shougo** [comment]
Yes.  This is intended behavior.
